title: Anton Moiseev
description: >
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

url: "http://antonmoiseev.com"
baseurl: ""
email: a@antonmoiseev.com
github_username: antonmoiseev
twitter_username: antonmoiseev

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-redirect-from
  - jemoji

exclude: [
  build,
  serve,
  Gemfile,
  Gemfile.lock,
  README.md
]
